# Generated by Django 6.0.3 on 2026-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=500)),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('quartile', models.CharField(blank=True, max_length=10)),
                ('sjr', models.FloatField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('plan', models.CharField(blank=True, max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('focus', models.CharField(default='General / Best Fit', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
