# Generated by Django 4.2.11 on 2026-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='search',
            name='search_mode',
            field=models.CharField(default='abstract', max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
